spring.application.name=springai


spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.organization-id=${OPENAI_ORGANIZATION_ID}
spring.ai.openai.project-id=${OPENAI_PROJECT_ID}
spring.ai.openai.chat.options.model=gpt-4o




logging.level.org.springframework.web=DEBUG